name = "image-proxy"
main = "src/index.js"
compatibility_date = "2023-12-18"
workers_dev=true


# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
REMOTE_DATA_ADDRESS=""

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = "BLOG_PICTURE"
bucket_name = "blog-picture"

[[analytics_engine_datasets]]
binding = "PICTURE_ANALYSIS"
dataset = "picture"